# Generated by Django 5.0.14 on 2026-01-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
