# Generated by Django 5.0.14 on 2026-02-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector_notifications', '0002_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='only_interests',
            field=models.BooleanField(default=False),
        ),
    ]
